# Generated by Django 3.2.15 on 2022-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0002_deposit_history_created_dated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('package_type', models.CharField(choices=[('Apex', 'Apex'), ('Max', 'Max')], default='Apex', max_length=30)),
                ('duration', models.PositiveIntegerField(default=7)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
