# Generated by Django 3.2.15 on 2022-09-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0003_special_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='special_membership',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Deluxe', 'Deluxe'), ('Executive', 'Executive'), ('Ultimate', 'Ultimate'), ('Platinum', 'Platinum')], default='Classic', max_length=30),
        ),
    ]
