# Generated by Django 3.2.15 on 2022-09-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0005_auto_20220907_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_ip',
            old_name='loc',
            new_name='ascode',
        ),
        migrations.AddField(
            model_name='user_ip',
            name='countryCode',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user_ip',
            name='isp',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user_ip',
            name='lat',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user_ip',
            name='lon',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
