# Generated by Django 3.2.15 on 2022-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0006_auto_20220907_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_history',
            name='bep',
            field=models.CharField(default='wallet address', max_length=700),
        ),
        migrations.AddField(
            model_name='deposit_history',
            name='btc',
            field=models.CharField(default='wallet address', max_length=700),
        ),
        migrations.AddField(
            model_name='deposit_history',
            name='erc',
            field=models.CharField(default='wallet address', max_length=700),
        ),
        migrations.AddField(
            model_name='deposit_history',
            name='eth',
            field=models.CharField(default='wallet address', max_length=700),
        ),
        migrations.AddField(
            model_name='deposit_history',
            name='trc',
            field=models.CharField(default='wallet address', max_length=700),
        ),
    ]
