# Generated by Django 3.2.15 on 2022-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0007_auto_20220922_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.CharField(default='wallet address', max_length=700)),
                ('eth', models.CharField(default='wallet address', max_length=700)),
                ('erc', models.CharField(default='wallet address', max_length=700)),
                ('trc', models.CharField(default='wallet address', max_length=700)),
                ('bep', models.CharField(default='wallet address', max_length=700)),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit_history',
            name='bep',
        ),
        migrations.RemoveField(
            model_name='deposit_history',
            name='btc',
        ),
        migrations.RemoveField(
            model_name='deposit_history',
            name='erc',
        ),
        migrations.RemoveField(
            model_name='deposit_history',
            name='eth',
        ),
        migrations.RemoveField(
            model_name='deposit_history',
            name='trc',
        ),
    ]
